apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-deployment
spec:
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: lscr.io/linuxserver/sonarr:latest
        imagePullPolicy: IfNotPresent
        name: sonarr
        ports:
        - containerPort: 8989
          protocol: TCP
        volumeMounts:
        - mountPath: /tv
          name: sonarr-media
        - mountPath: /downloads
          name: sonarr-media
        - mountPath: /config
          name: sonarr-config
      initContainers:
        - name: prometheus-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/downloads"]
          volumeMounts:
          - mountPath: /prometheus
            name: prometheus-storage-volume
      volumes:
      - name: sonarr-media
        persistentVolumeClaim:
          claimName: sonarr-media
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config
