---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sonarr-config"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sonarr-media"
