---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/plex-config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  storageClassName: manual
  capacity:
    storage: 130Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.202
    path: "/mnt/hdd1"
