---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - env:
<<<<<<< HEAD
        - name: PLEX_CLAIM
          value: claim-t7iD9MYyxMbSEbCfoovA
=======
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - PLEX_CLAIM: CLAIM
          value: "claim-t7iD9MYyxMbSEbCfoovA"
>>>>>>> aa68cb55653236b6df9a5073001a43fabb19295a
        image: plexinc/pms-docker
        imagePullPolicy: IfNotPresent
        name: plex
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /data/media
          name: media
          readOnly: True
        - mountPath: /config
          name: plex-config
      initContainers:
       - name: plex-data-permission-fix
         image: busybox
         command: ["/bin/chmod","-R","777", "/config"]
         volumeMounts:
         - mountPath: /config
           name: plex-config
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: plex-media
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
