---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 130Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
