---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: lscr.io/linuxserver/plex:latest
        imagePullPolicy: IfNotPresent
        name: plex
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /data/media
          name: media
          readOnly: True
        - mountPath: /config
          name: plex-config
      initContainers:
       - name: plex-data-permission-fix
         image: busybox
         command: ["/bin/chmod","-R","777", "/config"]
         volumeMounts:
         - mountPath: /config
           name: plex-config
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: plex-media
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
