apiVersion: v1
kind: Service
metadata:
  labels:
  name: kube-state-metrics
  annotations:
      prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
  - name: telemetry
    port: 8081
    targetPort: 8081
  selector:
    name: kube-state-metrics
