apiVersion: v1
kind: Service
metadata:
  labels:
  name: kube-state-metrics
  namespace: kube-system
  annotations:
      prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics
    port: 7080
    targetPort: 7080
  - name: telemetry
    port: 7081
    targetPort: 7081
  selector:
    name: kube-state-metrics
