apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      name: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-state-metrics
  template:
    metadata:
      labels:
        name: kube-state-metrics
    spec:
      automountServiceAccountToken: true
      containers:
      - image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.3.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry
