ansibletarget1@master-node:/mnt/nfs/music/kube-state-metrics-configs$ cat service.yaml 
apiVersion: v1
kind: Service
metadata:
  labels:
  name: kube-state-metrics
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    name: kube-state-metrics
