---

apiVersion: v1
kind: Service
metadata:
  name: radarr-svc
spec:
  selector:
    app: radarr
  type: NodePort
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
      nodePort: 30878
