---

apiVersion: v1
kind: Service
metadata:
  name: radarr-svc
spec:
  selector:
    app: radarr
  type: NodePort
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
      nodePort: 30989
