---

apiVersion: v1
kind: Service
metadata:
  name: jackett-svc
spec:
  selector:
    app: jackett
  type: NodePort
  ports:
    - protocol: TCP
      port: 9117
      targetPort: 9117
      nodePort: 30117
