apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett-deployment
spec:
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: lscr.io/linuxserver/jackett:latest
        imagePullPolicy: IfNotPresent
        name: jackett
        ports:
        - containerPort: 9117
          protocol: TCP
        volumeMounts:
        - mountPath: /movies
          name: jackett-media
        - mountPath: /downloads
          name: jackett-media
        - mountPath: /config
          name: jackett-config
      volumes:
      - name: jackett-media
        persistentVolumeClaim:
          claimName: sonarr-media
      - name: jackett-config
        persistentVolumeClaim:
          claimName: jackett-config
