apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbhydra2-deployment
spec:
  selector:
    matchLabels:
      app: nzbhydra2
  template:
    metadata:
      labels:
        app: nzbhydra2
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: lscr.io/linuxserver/nzbhydra2:latest 
        imagePullPolicy: IfNotPresent
        name: nzbhydra2
        ports:
        - containerPort: 5076
          protocol: TCP
        volumeMounts:
        - mountPath: /movies
          name: nzbhydra2-media
        - mountPath: /downloads
          name: nzbhydra2-media
        - mountPath: /config
          name: nzbhydra2-config
      volumes:
      - name: nzbhydra2-media
        persistentVolumeClaim:
          claimName: sonarr-media
      - name: nzbhydra2-config
        persistentVolumeClaim:
          claimName: nzbhydra2-config
