---

apiVersion: v1
kind: Service
metadata:
  name: nzbhydra2-svc
spec:
  selector:
    app: nzbhydra2
  type: NodePort
  ports:
    - protocol: TCP
      port: 5076
      targetPort: 5076
      nodePort: 30076
