apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: blog-example
        image: busybox
        command: ["/bin/sh", "-c", "while true; do ls /mnt/blog-example; sleep 10;done"]
        volumeMounts:
          - mountPath: "/mnt/blog-example"
            name: blog-example
      volumes:
        - name: jellyfin
          persistentVolumeClaim:
            claimName: jellyfin
