---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
      nodePort: 30896
