apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin
spec:
  storageClassName: manual
  capacity:
    storage: 145Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: synology.local
    path: "/mnt/hdd1"
