apiVersion: v1
kind: Service
metadata:
  name: chronograf-service
spec:
  selector:
    app: chronograf
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088
