apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf-deployment
spec:
  selector:
    matchLabels:
      app: chronograf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
        - image: chronograf
          name: chronograf
          ports:
            - containerPort: 8888
