apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  selector:
    app: telegraf
  type: NodePort
  ports:
    - protocol: TCP
      port: 57000
      targetPort: 57000
      nodePort: 30700
