apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/influxdb"
