apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzd-deployment
spec:
  selector:
    matchLabels:
      app: sabnzd
  template:
    metadata:
      labels:
        app: sabnzd
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: lscr.io/linuxserver/sabnzbd:latest
        imagePullPolicy: IfNotPresent
        name: sabnzd
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /movies
          name: sabnzd-media
        - mountPath: /downloads
          name: sabnzd-media
        - mountPath: /config
          name: sabnzd-config
      volumes:
      - name: sabnzd-media
        persistentVolumeClaim:
          claimName: sonarr-media
      - name: sabnzd-config
        persistentVolumeClaim:
          claimName: sabnzd-config
