---

apiVersion: v1
kind: Service
metadata:
  name: sabnzd-svc
spec:
  selector:
    app: sabnzd
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30808
