---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzd-config
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sabnzd-config"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzd-media
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.202
    path: "/mnt/hdd1"
